config/routes.rb
Bookshelf::Application.routes.draw do

  resources :books do
    resources :comments, :only => :create
  end 

  resource :admin_session

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :login
  attr_accessible :password
  attr_accessible :password_confirmation	

  acts_as_authentic   #telling the admin model that it uses authlogic
end

app/models/admin_session.rb
class AdminSession < Authlogic::Session::Base
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :thoughts, :title
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :author, :text
  belongs_to :book
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController
	def new
		@admin_session = AdminSession.new 
	end

	def create
		@admin_session = AdminSession.new(params[:admin_session])
		if @admin_session.save
			flash[:notice] = "Login successful!"
			redirect_to books_path
		else
			render :new
		end
	end

	def destroy
		current_admin_session.destroy
		flash[:notice] = "Logout successful!"
		redirect_to books_path
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper :all
  protect_from_forgery

  helper_method :current_admin_session, :current_admin

  private
  def current_admin_session
  	return @current_admin_session if defined?(@current_admin_session)
  	@current_admin_session = AdminSession.find
  end

  def current_admin
  	return @current_admin if defined?(@current_admin)
  	@current_admin = current_admin_session && current_admin_session.admin
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_filter :login_required, :except => [:index, :show]

	def index
		@books =  Book.paginate :page => params[:page], :per_page => 8
	end

	def show
		@book = Book.find(params[:id])
		@comments = @book.comments.paginate :page => params[:page], :per_page => 5, :order => 'created_at ASC'  
	end

	def new
		@book = Book.new
	end

	# form.submit generates : POST '/books' which is routed to books#create. The POST contains the object associated with form_for as the parameter. 
	# The object as parameter in hash format i.e :book={"title" => "Wings of fire", "thoughts" => "Good One !!!"}.  
	def create
		book = Book.new(params[:book])  # form_for posts the entire model associated with it as the parameter in hash format. So we read that hash value (i.e :book) and create a book object out of it. 
		if book.save
			flash[:notice] = "#{book.title} saved."
			redirect_to book_path(book)
		else
			redirect :new			
		end                 
	end	

	def edit
		@book = Book.find(params[:id]) 
	end

	def update
		book = Book.find(params[:id])
		if book.update_attributes(params[:book])
			flash[:notice] = "#{book.title} saved."
			redirect_to book_path(book)	#This is similiar to writing -> redirect_to @book		
		else
			render :edit
		end
	end

	def destroy
		book = Book.find(params[:id])
		book.destroy
		flash[:notice] = "#{book.title} deleted"
		redirect_to books_path
	end

	private
	def login_required
		unless current_admin
			flash[:error] = 'Only logged in admins can access this page.'
			redirect_to books_path
		end	
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		book = Book.find(params[:book_id])
		comment = book.comments.new(params[:comment])
		comment.save
		flash[:notice] = 'Comments saved'
		redirect_to book_path(book)
	end
end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/admin_sessions/new.html.erb
<% title 'Login' %>
<%= form_for @admin_session, :url => admin_session_path do |f| %>
	<%= f.error_messages %>
	<p>
		<%= f.label :login %>
		<%= f.text_field :login %>
	</p>	

	<p>
		<%= f.label :pasword %>
		<%= f.text_field :password %>
	</p>	

	<%= f.submit "Login" %>
<% end %>

app/views/books/edit.html.erb
<% title "Editing: #{@book.title}" %>
<%= form_for(@book) do |form| %>
	<p>
		<%= form.label :title %><br/>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :thoughts %><br/>
		<%= form.text_area :thoughts %>
	</p>
	<%= form.submit %>
<% end %>	

app/views/books/index.html.erb
<% title '~ My Books ~' %>
<% @books.each do |book| %>
	<h2><%= link_to book.title, book_path(book) %></h2>
	<p><%= book.thoughts %></p>
<% end %>

<%= will_paginate @books %>

<% if current_admin %>
<p>
	Admin actions : <%= link_to "New Book", new_book_path %>
</p>
<% end %>

app/views/books/new.html.erb
<% title 'New Book' %>

<%= form_for(@book) do |form| %>
	<p>
		<%= form.label :title %></br>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :thoughts %></br>
		<%= form.text_area :thoughts %>
	</p>
	<%= form.submit %>	
<% end %>

app/views/books/show.html.erb
<% title @book.title %>
<h2> <%= link_to @book.title, book_path(@book) %> </h2>
<p> <%= @book.thoughts %> </p>

<% if @comments %>
	<h3> Comments </h3>
	<% @comments.each do |comment| %>
		<p><strong> <%= comment.author %></strong> : <%= comment.text %>
	<% end %>
	<%= will_paginate @comments %>
<% end %>		 

<h3>Post Your Comments</h3>
<%= form_for  [@book, Comment.new] do |form| %>
	<%= form.label :author, 'Author' %>
	<p><%= form.text_field :author %></p>
	<p><%= form.label 'Comment' %></p>
	<p><%= form.text_area :text %></p>
	<%= form.submit 'Save' %>
<% end %>	

<% if current_admin %>
<p>
	Admin Actions :
	<%= link_to 'Edit', edit_book_path(@book) %> | 
	<%= link_to 'Delete', book_path(@book), :method => :delete, :confirm => "Are you sure?" %> |
	<%= link_to "Back", books_path %>
</p>
<% end %>	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag :all %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
       <% if current_admin %>
        <p>
            <%= link_to "Logout", admin_session_path(current_admin_session), :method => :delete %>
        </p>
      <% else %>
        <p>
            <%= link_to "Login", new_admin_session_path %>
        </p>
      <% end %>
      
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>